#!/usr/bin/env node
/**
 * react-icons shim generator
 *
 * 扫描所有 `import { Xxx } from "react-icons/yy"`，
 * 从 react-icons 的 index.mjs 中**提取**用到图标的 SVG 数据，
 * 生成一个独立的代理文件供 webpack alias 替换原始子包。
 *
 * 这样 webpack 只会打包真正用到的图标定义（而不是整个 5MB 的 index.mjs）。
 *
 * 当源码新增 react-icons 图标时，需重跑：
 *   node tools/react-icons-shim/generate.js
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "../..");
const OUT = path.resolve(__dirname, "dist");
const RI_ROOT = path.resolve(ROOT, "node_modules/react-icons");

// 1. 扫描源码收集图标使用
const rg = execSync(
  `grep -rohE "import\\s*\\{[^}]+\\}\\s*from\\s*['\\"]react-icons/[a-z0-9]+['\\"]" apps libs 2>/dev/null || true`,
  { cwd: ROOT, encoding: "utf8" },
);

const byLib = {};
for (const line of rg.trim().split("\n")) {
  const m = line.match(
    /\{\s*([^}]+)\s*\}\s*from\s*['"]react-icons\/([a-z0-9]+)['"]/,
  );
  if (m) {
    const lib = m[2];
    const names = m[1]
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (!byLib[lib]) byLib[lib] = new Set();
    names.forEach((n) => byLib[lib].add(n));
  }
}

if (!fs.existsSync(OUT)) fs.mkdirSync(OUT, { recursive: true });

// 2. 为每个 lib 解析 index.mjs，提取被使用的图标
let totalExtracted = 0;
const generatedLibs = Object.keys(byLib).sort();

for (const lib of generatedLibs) {
  const need = byLib[lib];
  const src = fs.readFileSync(
    path.join(RI_ROOT, lib, "index.mjs"),
    "utf8",
  );
  // 解析每个 export function NAME (props) { return GenIcon({...})(props); };
  const re = /export function (\w+)\s*\(props\)\s*\{\s*return GenIcon\(([\s\S]*?)\)\(props\);\s*\};?/g;
  const collected = [];
  let m;
  while ((m = re.exec(src)) !== null) {
    if (need.has(m[1])) {
      collected.push({ name: m[1], data: m[2].trim() });
    }
  }
  if (collected.length !== need.size) {
    const got = new Set(collected.map((c) => c.name));
    const missing = [...need].filter((n) => !got.has(n));
    console.warn(
      `[warn] lib=${lib}: requested ${need.size} icons but only matched ${collected.length}. Missing: ${missing.join(", ")}`,
    );
  }

  const lines = [
    "// AUTO-GENERATED by tools/react-icons-shim/generate.js",
    "// Do not edit. Re-run the generator after adding new react-icons imports.",
    'import { GenIcon } from "react-icons/lib";',
    "",
    ...collected.map(
      (c) =>
        `export function ${c.name}(props){return GenIcon(${c.data})(props);}`,
    ),
    "",
  ];
  fs.writeFileSync(path.join(OUT, `${lib}.mjs`), lines.join("\n"));
  totalExtracted += collected.length;
}

console.log(
  `Generated shim for ${generatedLibs.length} libraries / ${totalExtracted} icons:`,
);
for (const lib of generatedLibs) {
  console.log(`  react-icons/${lib} -> ${byLib[lib].size} icons`);
}
