# Generated by Django 5.1.10 on 2026-01-12 10:03

import django.db.models.deletion
import plans.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                ("project_id", models.PositiveIntegerField(verbose_name="project id")),
                (
                    "project_title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="project title"
                    ),
                ),
                (
                    "data_types",
                    models.JSONField(
                        default=dict, null=True, verbose_name="data_types"
                    ),
                ),
                (
                    "parsed_label_config",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Parsed label config in JSON format. See more about it in documentation",
                        null=True,
                        verbose_name="parsed label config",
                    ),
                ),
                ("label_config_hash", models.BigIntegerField(default=None, null=True)),
                ("quantity", models.IntegerField(default=1, verbose_name="quantity")),
                ("status", models.IntegerField(default=0, verbose_name="status")),
                ("failed", models.BooleanField(default=False, verbose_name="failed")),
                (
                    "fail_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="fail_message"
                    ),
                ),
                (
                    "target_platform",
                    models.CharField(
                        max_length=255, null=True, verbose_name="target_platform"
                    ),
                ),
                ("epochs", models.IntegerField(default=100, verbose_name="epochs")),
                ("imgsz", models.IntegerField(default=608, verbose_name="imgsz")),
                (
                    "cancelled",
                    models.BooleanField(default=False, verbose_name="cancelled"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
            ],
            bases=(plans.mixins.PlanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlanRecords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="content")),
                (
                    "platform",
                    models.CharField(
                        max_length=255, null=True, verbose_name="platform"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time a task was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
    ]
