# Generated by Django 5.1.10 on 2026-06-07 13:56

import django.db.models.deletion
import plans.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("plans", "0001_initial"),
        ("plans", "0002_plan_completed_at_plan_started_at_alter_plan_status"),
        ("plans", "0003_alter_plan_options_plan_batch_last_plan_box_loss_and_more"),
        ("plans", "0004_plan_training_config"),
        ("plans", "0005_add_training_pid"),
    ]

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                ("project_id", models.PositiveIntegerField(verbose_name="project id")),
                (
                    "project_title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="project title"
                    ),
                ),
                (
                    "data_types",
                    models.JSONField(
                        default=dict, null=True, verbose_name="data_types"
                    ),
                ),
                (
                    "parsed_label_config",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Parsed label config in JSON format. See more about it in documentation",
                        null=True,
                        verbose_name="parsed label config",
                    ),
                ),
                ("label_config_hash", models.BigIntegerField(default=None, null=True)),
                ("quantity", models.IntegerField(default=1, verbose_name="quantity")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Released"),
                            (2, "Confirmed"),
                            (3, "FileReady"),
                            (4, "Running"),
                            (6, "Failed"),
                            (9, "Completed"),
                            (-1, "Cancelled"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                ("failed", models.BooleanField(default=False, verbose_name="failed")),
                (
                    "fail_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="fail_message"
                    ),
                ),
                (
                    "target_platform",
                    models.CharField(
                        max_length=255, null=True, verbose_name="target_platform"
                    ),
                ),
                ("epochs", models.IntegerField(default=100, verbose_name="epochs")),
                ("imgsz", models.IntegerField(default=608, verbose_name="imgsz")),
                (
                    "cancelled",
                    models.BooleanField(default=False, verbose_name="cancelled"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(null=True, verbose_name="completed at"),
                ),
                (
                    "started_at",
                    models.DateTimeField(null=True, verbose_name="started at"),
                ),
                (
                    "batch_last",
                    models.IntegerField(
                        default=0, null=True, verbose_name="batch_last"
                    ),
                ),
                (
                    "box_loss",
                    models.FloatField(default=0, null=True, verbose_name="box_loss"),
                ),
                (
                    "box_precision",
                    models.FloatField(
                        default=0, null=True, verbose_name="box_precision"
                    ),
                ),
                (
                    "box_recall",
                    models.FloatField(default=0, null=True, verbose_name="box_recall"),
                ),
                (
                    "m_precision",
                    models.FloatField(default=0, null=True, verbose_name="m_precision"),
                ),
                (
                    "m_recall",
                    models.FloatField(default=0, null=True, verbose_name="m_recall"),
                ),
                (
                    "seg_loss",
                    models.FloatField(default=0, null=True, verbose_name="seg_loss"),
                ),
                (
                    "training_config",
                    models.CharField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="training_config",
                    ),
                ),
                (
                    "training_pid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="training_pid"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(plans.mixins.PlanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlanRecords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="content")),
                (
                    "platform",
                    models.CharField(
                        max_length=255, null=True, verbose_name="platform"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time a task was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingEpochs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.PositiveIntegerField(verbose_name="batch no")),
                ("epoch", models.PositiveIntegerField(verbose_name="epoch")),
                ("time", models.FloatField(null=True, verbose_name="time")),
                ("box_loss", models.FloatField(default=0, verbose_name="box loss")),
                ("seg_loss", models.FloatField(default=0, verbose_name="seg loss")),
                ("cls_loss", models.FloatField(default=0, verbose_name="class loss")),
                ("dfl_loss", models.FloatField(default=0, verbose_name="dfl loss")),
                (
                    "box_precision",
                    models.FloatField(default=0, verbose_name="box precision"),
                ),
                ("box_recall", models.FloatField(default=0, verbose_name="box recall")),
                ("box_map50", models.FloatField(default=0, verbose_name="box map50")),
                ("box_map95", models.FloatField(default=0, verbose_name="box map95")),
                (
                    "m_precision",
                    models.FloatField(default=0, verbose_name="m_precision"),
                ),
                ("m_recall", models.FloatField(default=0, verbose_name="m_recall")),
                ("m_map50", models.FloatField(default=0, verbose_name="m_map50")),
                ("m_map95", models.FloatField(default=0, verbose_name="m_map95")),
                ("v_box_loss", models.FloatField(default=0, verbose_name="v_box_loss")),
                ("v_seg_loss", models.FloatField(default=0, verbose_name="v_seg_loss")),
                ("v_cls_loss", models.FloatField(default=0, verbose_name="v_cls_loss")),
                ("v_dfl_loss", models.FloatField(default=0, verbose_name="v_dfl_loss")),
                ("lr_pg0", models.FloatField(default=0, verbose_name="lr_pg0")),
                ("lr_pg1", models.FloatField(default=0, verbose_name="lr_pg1")),
                ("lr_pg2", models.FloatField(default=0, verbose_name="lr_pg2")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time a record was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingModels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.PositiveIntegerField(verbose_name="batch no")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "label_type",
                    models.CharField(max_length=255, verbose_name="label type"),
                ),
                (
                    "model_kind",
                    models.CharField(max_length=255, verbose_name="model kind"),
                ),
                ("path", models.CharField(max_length=255, verbose_name="path")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time a record was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
    ]
