# Generated by Django 5.1.10 on 2026-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="completed_at",
            field=models.DateTimeField(null=True, verbose_name="completed at"),
        ),
        migrations.AddField(
            model_name="plan",
            name="started_at",
            field=models.DateTimeField(null=True, verbose_name="started at"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Released"),
                    (2, "Confirmed"),
                    (3, "FileReady"),
                    (4, "Running"),
                    (6, "Failed"),
                    (9, "Completed"),
                    (-1, "Cancelled"),
                ],
                default=0,
                verbose_name="status",
            ),
        ),
    ]
