# Generated by Django 5.1.10 on 2026-01-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_completed_at_plan_started_at_alter_plan_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AddField(
            model_name="plan",
            name="batch_last",
            field=models.IntegerField(default=0, null=True, verbose_name="batch_last"),
        ),
        migrations.AddField(
            model_name="plan",
            name="box_loss",
            field=models.FloatField(default=0, null=True, verbose_name="box_loss"),
        ),
        migrations.AddField(
            model_name="plan",
            name="box_precision",
            field=models.FloatField(default=0, null=True, verbose_name="box_precision"),
        ),
        migrations.AddField(
            model_name="plan",
            name="box_recall",
            field=models.FloatField(default=0, null=True, verbose_name="box_recall"),
        ),
        migrations.AddField(
            model_name="plan",
            name="m_precision",
            field=models.FloatField(default=0, null=True, verbose_name="m_precision"),
        ),
        migrations.AddField(
            model_name="plan",
            name="m_recall",
            field=models.FloatField(default=0, null=True, verbose_name="m_recall"),
        ),
        migrations.AddField(
            model_name="plan",
            name="seg_loss",
            field=models.FloatField(default=0, null=True, verbose_name="seg_loss"),
        ),
        migrations.CreateModel(
            name="TrainingEpochs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.PositiveIntegerField(verbose_name="batch no")),
                ("epoch", models.PositiveIntegerField(verbose_name="epoch")),
                ("time", models.FloatField(null=True, verbose_name="time")),
                ("box_loss", models.FloatField(default=0, verbose_name="box loss")),
                ("seg_loss", models.FloatField(default=0, verbose_name="seg loss")),
                ("cls_loss", models.FloatField(default=0, verbose_name="class loss")),
                ("dfl_loss", models.FloatField(default=0, verbose_name="dfl loss")),
                (
                    "box_precision",
                    models.FloatField(default=0, verbose_name="box precision"),
                ),
                ("box_recall", models.FloatField(default=0, verbose_name="box recall")),
                ("box_map50", models.FloatField(default=0, verbose_name="box map50")),
                ("box_map95", models.FloatField(default=0, verbose_name="box map95")),
                (
                    "m_precision",
                    models.FloatField(default=0, verbose_name="m_precision"),
                ),
                ("m_recall", models.FloatField(default=0, verbose_name="m_recall")),
                ("m_map50", models.FloatField(default=0, verbose_name="m_map50")),
                ("m_map95", models.FloatField(default=0, verbose_name="m_map95")),
                ("v_box_loss", models.FloatField(default=0, verbose_name="v_box_loss")),
                ("v_seg_loss", models.FloatField(default=0, verbose_name="v_seg_loss")),
                ("v_cls_loss", models.FloatField(default=0, verbose_name="v_cls_loss")),
                ("v_dfl_loss", models.FloatField(default=0, verbose_name="v_dfl_loss")),
                ("lr_pg0", models.FloatField(default=0, verbose_name="lr_pg0")),
                ("lr_pg1", models.FloatField(default=0, verbose_name="lr_pg1")),
                ("lr_pg2", models.FloatField(default=0, verbose_name="lr_pg2")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time a record was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingModels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.PositiveIntegerField(verbose_name="batch no")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "label_type",
                    models.CharField(max_length=255, verbose_name="label type"),
                ),
                (
                    "model_kind",
                    models.CharField(max_length=255, verbose_name="model kind"),
                ),
                ("path", models.CharField(max_length=255, verbose_name="path")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time a record was updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
    ]
