# Generated by Django 5.1.10 on 2026-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plan_options_plan_batch_last_plan_box_loss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="training_config",
            field=models.CharField(
                blank=True, max_length=10000, null=True, verbose_name="training_config"
            ),
        ),
    ]
