# Generated by Django 5.1.10 on 2026-06-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_plan_training_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="training_pid",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="training_pid"
            ),
        ),
    ]