# Generated by Django 5.1.10 on 2026-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_add_training_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="last_heartbeat",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last heartbeat"
            ),
        ),
    ]
