# Generated by Django 5.1.10 on 2026-06-08 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_add_last_heartbeat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # TrainingModels: add deployment status fields
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed",
            field=models.BooleanField(default=False, verbose_name="deployed"),
        ),
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deployed at"
            ),
        ),
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="deployed path"
            ),
        ),
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed_to_project",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="deployed to project"
            ),
        ),
        # TrainingModels: update Meta options
        migrations.AlterModelOptions(
            name="trainingmodels",
            options={
                "verbose_name": "training model",
                "verbose_name_plural": "training models",
            },
        ),
        # DeploymentHistory: create table (one project = one deployed model)
        migrations.CreateModel(
            name="DeploymentHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.PositiveIntegerField(verbose_name="project id")),
                (
                    "project_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="project title",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="deployed at"),
                ),
                (
                    "deployed_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="deployed path",
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deployed by",
                    ),
                ),
                (
                    "training_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_history",
                        to="plans.trainingmodels",
                        verbose_name="training model",
                    ),
                ),
            ],
            options={
                "verbose_name": "deployment history",
                "verbose_name_plural": "deployment histories",
                "ordering": ["-deployed_at"],
                "unique_together": {("project_id",)},
            },
        ),
    ]
