# Generated by Django 5.1.10 on 2026-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_add_last_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed",
            field=models.BooleanField(default=False, verbose_name="deployed"),
        ),
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deployed at"
            ),
        ),
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="deployed path"
            ),
        ),
        migrations.AddField(
            model_name="trainingmodels",
            name="deployed_to_project",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="deployed to project"
            ),
        ),
    ]
