# title: Semantic Segmentation with Masks
# type: community
# group: Computer Vision
# order: 2
# image: /static/templates/semantic-segmentation-with-masks.png
# details: <h1>Draw masks around the object with the brush tool</h1>
# config: |
#   <View>
#     <Image name="image" value="$image" zoom="true"/>
#     <BrushLabels name="tag" toName="image">
#       <Label value="Airplane" background="rgba(255, 0, 0, 0.7)"/>
#       <Label value="Car" background="rgba(0, 0, 255, 0.7)"/>
#     </BrushLabels>
#   </View>

title: 基于遮罩的语义分割
type: community
group: Computer Vision
order: 2
image: /static/templates/semantic-segmentation-with-masks.png
details: <h1>使用画笔工具在物体周围绘制遮罩</h1>
config: |
  <View>
    <Image name="image" value="$image" zoom="true"/>
    <BrushLabels name="tag" toName="image">
      <Label value="Airplane" alias="飞机" background="rgba(255, 0, 0, 0.7)"/>
      <Label value="Car" alias="汽车" background="rgba(0, 0, 255, 0.7)"/>
    </BrushLabels>
  </View>
