# Generated by Django 5.1.10 on 2026-01-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_auto_20221221_1101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("PROJECT_CREATED", "Project created"),
                    ("PROJECT_UPDATED", "Project updated"),
                    ("PROJECT_DELETED", "Project deleted"),
                    ("TASKS_CREATED", "Task created"),
                    ("TASKS_DELETED", "Task deleted"),
                    ("PLAN_CREATED", "Plan created"),
                    ("PLAN_DELETED", "Task deleted"),
                    ("ANNOTATION_CREATED", "Annotation created"),
                    ("ANNOTATIONS_CREATED", "Annotations created"),
                    ("ANNOTATION_UPDATED", "Annotation updated"),
                    ("ANNOTATIONS_DELETED", "Annotation deleted"),
                    ("LABEL_LINK_CREATED", "Label link created"),
                    ("LABEL_LINK_UPDATED", "Label link updated"),
                    ("LABEL_LINK_DELETED", "Label link deleted"),
                ],
                db_index=True,
                help_text="Action value",
                max_length=128,
                verbose_name="action of webhook",
            ),
        ),
    ]
