// Mock 数据
export const mockTrainedModels = {
  count: 24,
  results: [
    {
      id: 1,
      batch_no: 6,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/2/6/training-model.pt",
      updated_at: "2026-01-26 19:45:13.643012+00",
      plan_id: 2,
    },
    {
      id: 2,
      batch_no: 2,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/3/2/training-model.pt",
      updated_at: "2026-01-27 01:43:54.849029+00",
      plan_id: 3,
    },
    {
      id: 3,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/4/1/training-model.pt",
      updated_at: "2026-01-27 06:44:58.153701+00",
      plan_id: 4,
    },
    {
      id: 4,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/5/1/training-model.pt",
      updated_at: "2026-01-27 07:06:05.266067+00",
      plan_id: 5,
    },
    {
      id: 5,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/6/1/training-model.pt",
      updated_at: "2026-01-27 07:10:33.700121+00",
      plan_id: 6,
    },
    {
      id: 6,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/7/1/training-model.pt",
      updated_at: "2026-01-30 02:38:12.672478+00",
      plan_id: 7,
    },
    {
      id: 7,
      batch_no: 6,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/2/6/training-model.pt",
      updated_at: "2026-01-26 19:45:13.643012+00",
      plan_id: 2,
    },
    {
      id: 8,
      batch_no: 2,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/3/2/training-model.pt",
      updated_at: "2026-01-27 01:43:54.849029+00",
      plan_id: 3,
    },
    {
      id: 9,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/4/1/training-model.pt",
      updated_at: "2026-01-27 06:44:58.153701+00",
      plan_id: 4,
    },
    {
      id: 10,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/5/1/training-model.pt",
      updated_at: "2026-01-27 07:06:05.266067+00",
      plan_id: 5,
    },
    {
      id: 11,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/6/1/training-model.pt",
      updated_at: "2026-01-27 07:10:33.700121+00",
      plan_id: 6,
    },
    {
      id: 12,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/7/1/training-model.pt",
      updated_at: "2026-01-30 02:38:12.672478+00",
      plan_id: 7,
    },
    {
      id: 13,
      batch_no: 6,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/2/6/training-model.pt",
      updated_at: "2026-01-26 19:45:13.643012+00",
      plan_id: 2,
    },
    {
      id: 14,
      batch_no: 2,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/3/2/training-model.pt",
      updated_at: "2026-01-27 01:43:54.849029+00",
      plan_id: 3,
    },
    {
      id: 15,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/4/1/training-model.pt",
      updated_at: "2026-01-27 06:44:58.153701+00",
      plan_id: 4,
    },
    {
      id: 16,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/5/1/training-model.pt",
      updated_at: "2026-01-27 07:06:05.266067+00",
      plan_id: 5,
    },
    {
      id: 17,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/6/1/training-model.pt",
      updated_at: "2026-01-27 07:10:33.700121+00",
      plan_id: 6,
    },
    {
      id: 18,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/7/1/training-model.pt",
      updated_at: "2026-01-30 02:38:12.672478+00",
      plan_id: 7,
    },
    {
      id: 19,
      batch_no: 6,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/2/6/training-model.pt",
      updated_at: "2026-01-26 19:45:13.643012+00",
      plan_id: 2,
    },
    {
      id: 20,
      batch_no: 2,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/3/2/training-model.pt",
      updated_at: "2026-01-27 01:43:54.849029+00",
      plan_id: 3,
    },
    {
      id: 21,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/4/1/training-model.pt",
      updated_at: "2026-01-27 06:44:58.153701+00",
      plan_id: 4,
    },
    {
      id: 22,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/5/1/training-model.pt",
      updated_at: "2026-01-27 07:06:05.266067+00",
      plan_id: 5,
    },
    {
      id: 23,
      batch_no: 1,
      name: "ship-segment-with-ml",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/6/1/training-model.pt",
      updated_at: "2026-01-27 07:10:33.700121+00",
      plan_id: 6,
    },
    {
      id: 24,
      batch_no: 1,
      name: "ship-segment-sample",
      label_type: "PolygonLabels",
      model_kind: "segment",
      path: "/label-studio/data/training-model/7/1/training-model.pt",
      updated_at: "2026-01-30 02:38:12.672478+00",
      plan_id: 7,
    },
  ],
};
