// export const DEFAULT_HOTKEYS = [
//   // Annotation Controls
//   {
//     id: 100,
//     section: "annotation",
//     element: "annotation:submit",
//     label: "Submit Annotation",
//     key: "ctrl+enter",
//     description: "Submit the current annotation",
//     active: true,
//   },
//   {
//     id: 200,
//     section: "annotation",
//     element: "annotation:skip",
//     label: "Skip Task",
//     key: "ctrl+space",
//     description: "Skip the current task",
//     active: true,
//   },
//   {
//     id: 300,
//     section: "annotation",
//     element: "annotation:undo",
//     label: "Undo",
//     key: "ctrl+z",
//     description: "Undo last action",
//     active: true,
//   },
//   {
//     id: 400,
//     section: "annotation",
//     element: "annotation:redo",
//     label: "Redo",
//     key: "ctrl+shift+z",
//     description: "Redo previously undone action",
//     active: true,
//   },

//   // Data Manager
//   {
//     id: 500,
//     section: "data_manager",
//     element: "dm.focus-previous",
//     label: "Focus Previous Task",
//     key: "shift+up",
//     description: "Move focus to the previous task",
//     active: true,
//   },
//   {
//     id: 600,
//     section: "data_manager",
//     element: "dm.focus-next",
//     label: "Focus Next Task",
//     key: "shift+down",
//     description: "Move focus to the next task",
//     active: true,
//   },
//   {
//     id: 700,
//     section: "data_manager",
//     element: "dm.close-labeling",
//     label: "Focus Closed Task",
//     key: "shift+left",
//     description: "Focus on the closed task column",
//     active: true,
//   },
//   {
//     id: 800,
//     section: "data_manager",
//     element: "dm.open-labeling",
//     label: "Focus Open Task",
//     key: "shift+right",
//     description: "Focus on the open task column",
//     active: true,
//   },
//   {
//     id: 900,
//     section: "data_manager",
//     element: "dm.toggle-bulk-sidebar-minimization",
//     label: "Toggle Bulk Sidebar",
//     key: "shift+.",
//     description: "Minimize or expand bulk actions sidebar",
//     active: true,
//   },

//   // Region Management
//   {
//     id: 1100,
//     section: "regions",
//     element: "region:delete-all",
//     label: "Delete All Regions",
//     key: "ctrl+backspace",
//     description: "Remove all regions",
//     active: true,
//   },
//   {
//     id: 1200,
//     section: "regions",
//     element: "region:focus",
//     label: "Focus First Region",
//     key: "enter",
//     description: "Move focus to the first focusable region",
//     active: true,
//   },
//   {
//     id: 1300,
//     section: "regions",
//     element: "region:relation",
//     label: "Create Region Relation",
//     key: "alt+r",
//     description: "Create a relation between selected regions",
//     active: true,
//   },
//   {
//     id: 1400,
//     section: "regions",
//     element: "region:visibility",
//     label: "Toggle Region Visibility",
//     key: "alt+h",
//     description: "Show or hide the selected region",
//     active: true,
//   },
//   {
//     id: 1500,
//     section: "regions",
//     element: "region:visibility-all",
//     label: "Toggle All Region Visibility",
//     key: "ctrl+h",
//     description: "Show or hide all regions",
//     active: true,
//   },
//   {
//     id: 1600,
//     section: "regions",
//     element: "region:lock",
//     label: "Lock Region",
//     key: "alt+l",
//     description: "Lock or unlock the selected region",
//     active: true,
//   },
//   {
//     id: 1700,
//     section: "regions",
//     element: "region:meta",
//     label: "Edit Region Metadata",
//     key: "alt+m",
//     description: "Edit metadata for selected region",
//     active: true,
//   },
//   {
//     id: 1800,
//     section: "regions",
//     element: "region:unselect",
//     label: "Unselect Region",
//     key: "u",
//     description: "Deselect the currently selected region",
//     active: true,
//   },
//   {
//     id: 1900,
//     section: "regions",
//     element: "region:exit",
//     label: "Exit Region Mode",
//     key: "escape",
//     description: "Exit relation mode and unselect region",
//     active: true,
//   },
//   {
//     id: 2000,
//     section: "regions",
//     element: "region:delete",
//     label: "Delete Selected Region",
//     key: "backspace",
//     description: "Delete currently selected region",
//     active: true,
//   },
//   {
//     id: 2100,
//     section: "regions",
//     element: "region:cycle",
//     label: "Cycle Regions",
//     key: "alt+.",
//     description: "Cycle through all regions",
//     active: true,
//   },
//   {
//     id: 2200,
//     section: "regions",
//     element: "region:duplicate",
//     label: "Duplicate Region",
//     key: "ctrl+d",
//     description: "Create a copy of the selected region",
//     active: true,
//   },
//   {
//     id: 2300,
//     section: "regions",
//     element: "segment:delete",
//     label: "Delete Segment",
//     key: "delete",
//     description: "Delete selected segment",
//     active: true,
//   },

//   // Editor - Audio Controls
//   {
//     id: 2400,
//     section: "audio",
//     element: "audio:back",
//     label: "Rewind 1 Second",
//     key: "ctrl+b",
//     description: "Rewind the audio by 1 second",
//     active: true,
//   },
//   {
//     id: 2500,
//     section: "audio",
//     element: "audio:playpause",
//     label: "Play / Pause Audio",
//     key: "ctrl+p",
//     description: "Toggle audio playback",
//     active: true,
//   },
//   {
//     id: 2600,
//     section: "audio",
//     element: "audio:step-backward",
//     label: "Step Back",
//     key: "alt+a",
//     description: "Step back one frame",
//     active: true,
//   },
//   {
//     id: 2700,
//     section: "audio",
//     element: "audio:step-forward",
//     label: "Step Forward",
//     key: "alt+d",
//     description: "Step forward one frame",
//     active: true,
//   },

//   // Editor - Video Controls
//   {
//     id: 2800,
//     section: "video",
//     element: "media:playpause",
//     label: "Play / Pause Video",
//     key: "ctrl+alt+space",
//     description: "Toggle video playback",
//     active: true,
//   },
//   {
//     id: 2900,
//     section: "video",
//     element: "media:step-backward",
//     label: "Step Back",
//     key: "alt+left",
//     description: "Step one frame backward",
//     active: true,
//   },
//   {
//     id: 3000,
//     section: "video",
//     element: "media:step-forward",
//     label: "Step Forward",
//     key: "alt+right",
//     description: "Step one frame forward",
//     active: true,
//   },
//   {
//     id: 3100,
//     section: "video",
//     element: "video:keyframe-backward",
//     label: "Previous Keyframe",
//     key: "ctrl+alt+left",
//     description: "Jump to previous keyframe",
//     active: true,
//   },
//   {
//     id: 3200,
//     section: "video",
//     element: "video:keyframe-forward",
//     label: "Next Keyframe",
//     key: "ctrl+alt+right",
//     description: "Jump to next keyframe",
//     active: true,
//   },
//   {
//     id: 3300,
//     section: "video",
//     element: "video:backward",
//     label: "Seek Backward",
//     key: "alt+left",
//     description: "Seek video backward",
//     active: true,
//   },
//   {
//     id: 3400,
//     section: "video",
//     element: "video:rewind",
//     label: "First Frame",
//     key: "shift+ctrl+alt+left",
//     description: "Jump to first frame",
//     active: true,
//   },
//   {
//     id: 3500,
//     section: "video",
//     element: "video:forward",
//     label: "Seek Forward",
//     key: "shift+alt+right",
//     description: "Seek video forward",
//     active: true,
//   },
//   {
//     id: 3600,
//     section: "video",
//     element: "video:fastforward",
//     label: "Last Frame",
//     key: "shift+ctrl+alt+right",
//     description: "Jump to last frame",
//     active: true,
//   },
//   {
//     id: 3700,
//     section: "video",
//     element: "video:hop-backward",
//     label: "Hop Backward",
//     key: "shift+alt+left",
//     description: "Hop backward quickly",
//     active: true,
//   },
//   {
//     id: 3800,
//     section: "video",
//     element: "video:hop-forward",
//     label: "Hop Forward",
//     key: "shift+alt+right",
//     description: "Hop forward quickly",
//     active: true,
//   },

//   // Editor - Time Series Controls
//   {
//     id: 3900,
//     section: "timeseries",
//     element: "ts:grow-left",
//     label: "Extend Left",
//     key: "left",
//     description: "Extend the region to the left",
//     active: true,
//   },
//   {
//     id: 4000,
//     section: "timeseries",
//     element: "ts:grow-right",
//     label: "Extend Right",
//     key: "right",
//     description: "Extend the region to the right",
//     active: true,
//   },
//   {
//     id: 4100,
//     section: "timeseries",
//     element: "ts:shrink-left",
//     label: "Shrink Left",
//     key: "alt+left",
//     description: "Shrink the region from the left",
//     active: true,
//   },
//   {
//     id: 4200,
//     section: "timeseries",
//     element: "ts:shrink-right",
//     label: "Shrink Right",
//     key: "alt+right",
//     description: "Shrink the region from the right",
//     active: true,
//   },
//   {
//     id: 4300,
//     section: "timeseries",
//     element: "ts:grow-left-large",
//     label: "Extend Left (Large)",
//     key: "shift+left",
//     description: "Extend region left significantly",
//     active: true,
//   },
//   {
//     id: 4400,
//     section: "timeseries",
//     element: "ts:grow-right-large",
//     label: "Extend Right (Large)",
//     key: "shift+right",
//     description: "Extend region right significantly",
//     active: true,
//   },
//   {
//     id: 4500,
//     section: "timeseries",
//     element: "ts:shrink-left-large",
//     label: "Shrink Left (Large)",
//     key: "shift+alt+left",
//     description: "Shrink region from left significantly",
//     active: true,
//   },
//   {
//     id: 4600,
//     section: "timeseries",
//     element: "ts:shrink-right-large",
//     label: "Shrink Right (Large)",
//     key: "shift+alt+right",
//     description: "Shrink region from right significantly",
//     active: true,
//   },

//   // Image Gallery Controls
//   {
//     id: 4700,
//     section: "image_gallery",
//     element: "image:prev",
//     label: "Previous Image",
//     key: "ctrl+left",
//     description: "View previous image",
//     active: true,
//   },
//   {
//     id: 4800,
//     section: "image_gallery",
//     element: "image:next",
//     label: "Next Image",
//     key: "ctrl+right",
//     description: "View next image",
//     active: true,
//   },

//   {
//     id: 5000,
//     section: "tools",
//     element: "tool:zoom-in",
//     label: "Zoom In",
//     key: "ctrl+plus",
//     description: "Zoom in on the image",
//     active: true,
//   },
//   {
//     id: 5100,
//     section: "tools",
//     element: "tool:pan-image",
//     label: "Pan Image",
//     key: "H",
//     description: "Pan around the image",
//     active: true,
//   },
//   {
//     id: 5200,
//     section: "tools",
//     element: "tool:zoom-to-fit",
//     label: "Zoom to Fit",
//     key: "shift+1",
//     description: "Zoom to fit the full image in view",
//     active: true,
//   },
//   {
//     id: 5300,
//     section: "tools",
//     element: "tool:zoom-to-actual",
//     label: "Zoom to 100%",
//     key: "shift+2",
//     description: "Zoom to actual image size (100%)",
//     active: true,
//   },
//   {
//     id: 5400,
//     section: "tools",
//     element: "tool:zoom-out",
//     label: "Zoom Out",
//     key: "ctrl+minus",
//     description: "Zoom out of the image",
//     active: true,
//   },
//   {
//     id: 5401,
//     section: "tools",
//     element: "tool:move",
//     label: "Move Tool",
//     key: "V",
//     description: "Select the move tool to reposition annotations",
//     active: true,
//   },
//   {
//     id: 5402,
//     section: "tools",
//     element: "tool:brush",
//     label: "Brush Tool",
//     key: "B",
//     description: "Select the brush tool",
//     active: true,
//   },

//   {
//     id: 5500,
//     section: "tools",
//     element: "tool:ellipse",
//     label: "Ellipse Tool",
//     key: "O",
//     description: "Select the ellipse tool",
//     active: true,
//   },
//   {
//     id: 5600,
//     section: "tools",
//     element: "tool:eraser",
//     label: "Eraser Tool",
//     key: "E",
//     description: "Select the eraser tool",
//     active: true,
//   },
//   {
//     id: 5700,
//     section: "tools",
//     element: "tool:auto-detect",
//     label: "Auto Detect",
//     key: "M",
//     description: "Use the auto-detect tool to automatically suggest regions",
//     active: true,
//   },
//   {
//     id: 5900,
//     section: "tools",
//     element: "tool:key-point",
//     label: "Key Point Tool",
//     key: "K",
//     description: "Select the key point annotation tool",
//     active: true,
//   },
//   {
//     id: 6000,
//     section: "tools",
//     element: "tool:magic-wand",
//     label: "Magic Wand",
//     key: "W",
//     description: "Select the magic wand tool for smart region selection",
//     active: true,
//   },
//   {
//     id: 6100,
//     section: "tools",
//     element: "tool:polygon",
//     label: "Polygon Tool",
//     key: "P",
//     description: "Select the polygon annotation tool",
//     active: true,
//   },
//   {
//     id: 6200,
//     section: "tools",
//     element: "tool:rect",
//     label: "Rectangle Tool",
//     key: "R",
//     description: "Select the rectangle annotation tool",
//     active: true,
//   },
//   {
//     id: 6201,
//     section: "tools",
//     element: "tool:rect-3point",
//     label: "3-Point Rectangle",
//     key: "shift+R",
//     description: "Draw a rotated rectangle using 3-point selection",
//     active: true,
//   },

//   {
//     id: 6300,
//     section: "tools",
//     element: "tool:rotate-left",
//     label: "Rotate Left",
//     key: "alt+left",
//     description: "Rotate the image 90° to the left",
//     active: true,
//   },
//   {
//     id: 6400,
//     section: "tools",
//     element: "tool:rotate-right",
//     label: "Rotate Right",
//     key: "alt+right",
//     description: "Rotate the image 90° to the right",
//     active: true,
//   },
//   {
//     id: 6700,
//     section: "tools",
//     element: "tool:decrease-tool",
//     label: "Decrease Tool Size",
//     key: "[",
//     description: "Decrease tool size",
//     active: true,
//   },
//   {
//     id: 6800,
//     section: "tools",
//     element: "tool:increase-tool",
//     label: "Increase Tool Size",
//     key: "]",
//     description: "Increase tool size",
//     active: true,
//   },

//   // Paragraph Navigation
//   {
//     id: 6900,
//     section: "paragraphs",
//     element: "phrases:next-phrase",
//     label: "Next Phrase",
//     key: "ctrl+down",
//     description: "Navigate to the next phrase in paragraph view",
//     active: true,
//   },
//   {
//     id: 7000,
//     section: "paragraphs",
//     element: "phrases:previous-phrase",
//     label: "Previous Phrase",
//     key: "ctrl+up",
//     description: "Navigate to the previous phrase in paragraph view",
//     active: true,
//   },
//   {
//     id: 7100,
//     section: "paragraphs",
//     element: "phrases:select_all_annotate",
//     label: "Select All and Annotate",
//     key: "ctrl+shift+a",
//     description: "Select all text in current phrase and create annotation",
//     active: true,
//   },
//   {
//     id: 7200,
//     section: "paragraphs",
//     element: "phrases:next-region",
//     label: "Next Region in Phrase",
//     key: "ctrl+right",
//     description: "Navigate to the next region within current phrase",
//     active: true,
//   },
//   {
//     id: 7300,
//     section: "paragraphs",
//     element: "phrases:previous-region",
//     label: "Previous Region in Phrase",
//     key: "ctrl+left",
//     description: "Navigate to the previous region within current phrase",
//     active: true,
//   },
// ];

// export const HOTKEY_SECTIONS = [
//   {
//     id: "annotation",
//     title: "Annotation Actions",
//     description: "Shortcuts for common annotation tasks like submit, skip, undo and redo",
//   },

//   {
//     id: "data_manager",
//     title: "Data Manager",
//     description: "Shortcuts for navigating and managing tasks in Project's Data Manager",
//   },

//   {
//     id: "regions",
//     title: "Region Management",
//     description: "Shortcuts for creating, selecting and manipulating annotation regions",
//   },

//   {
//     id: "tools",
//     title: "Tools",
//     description: "Shortcuts for controlling tools panel when labeling images",
//   },

//   {
//     id: "audio",
//     title: "Audio Controls",
//     description: "Shortcuts for controlling audio playback and navigation",
//   },
//   {
//     id: "video",
//     title: "Video Controls",
//     description: "Shortcuts for controlling video playback and navigation",
//   },
//   {
//     id: "timeseries",
//     title: "Time Series Controls",
//     description: "Shortcuts for manipulating time series data regions",
//   },
//   {
//     id: "image_gallery",
//     title: "Image Gallery Navigation",
//     description: "Shortcuts for navigating between images in multi-image tasks",
//   },
//   {
//     id: "paragraphs",
//     title: "Paragraph Navigation",
//     description: "Shortcuts for navigating phrases and regions in paragraph/dialogue view",
//   },
// ];
export const DEFAULT_HOTKEYS = [
  // 标注控制
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: "提交标注",
    key: "ctrl+enter",
    description: "提交当前标注结果",
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: "跳过任务",
    key: "ctrl+space",
    description: "跳过当前标注任务",
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: "撤销操作",
    key: "ctrl+z",
    description: "撤销上一步操作",
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: "重做操作",
    key: "ctrl+shift+z",
    description: "恢复被撤销的操作",
    active: true,
  },

  // 数据管理器
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: "聚焦上一个任务",
    key: "shift+up",
    description: "将焦点移动到上一个任务",
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: "聚焦下一个任务",
    key: "shift+down",
    description: "将焦点移动到下一个任务",
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: "聚焦已关闭任务列",
    key: "shift+left",
    description: "聚焦到已关闭任务列",
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: "聚焦已打开任务列",
    key: "shift+right",
    description: "聚焦到已打开任务列",
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: "切换批量边栏",
    key: "shift+.",
    description: "最小化或展开批量操作边栏",
    active: true,
  },

  // 区域管理
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: "删除所有区域",
    key: "ctrl+backspace",
    description: "移除所有标注区域",
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: "聚焦首个区域",
    key: "enter",
    description: "将焦点移到第一个可聚焦区域",
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: "创建区域关联",
    key: "alt+r",
    description: "在选定区域之间创建关联关系",
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: "切换区域可见性",
    key: "alt+h",
    description: "显示或隐藏选定区域",
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: "切换所有区域可见性",
    key: "ctrl+h",
    description: "显示或隐藏所有区域",
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: "锁定/解锁区域",
    key: "alt+l",
    description: "锁定或解锁选定区域",
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: "编辑区域元数据",
    key: "alt+m",
    description: "编辑选定区域的元数据",
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: "取消选中区域",
    key: "u",
    description: "取消选中当前选定的区域",
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: "退出区域模式",
    key: "escape",
    description: "退出关联模式并取消选中区域",
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: "删除选中区域",
    key: "backspace",
    description: "删除当前选定的区域",
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: "循环切换区域",
    key: "alt+.",
    description: "在所有区域间循环切换焦点",
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: "复制区域",
    key: "ctrl+d",
    description: "创建选定区域的副本",
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: "删除片段",
    key: "delete",
    description: "删除选定的片段",
    active: true,
  },

  // 编辑器 - 音频控制
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: "后退1秒",
    key: "ctrl+b",
    description: "音频后退1秒",
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: "播放/暂停音频",
    key: "ctrl+p",
    description: "切换音频播放状态",
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: "后退一帧",
    key: "alt+a",
    description: "向后移动一帧",
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: "前进一帧",
    key: "alt+d",
    description: "向前移动一帧",
    active: true,
  },

  // 编辑器 - 视频控制
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: "播放/暂停视频",
    key: "ctrl+alt+space",
    description: "切换视频播放状态",
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: "后退一帧",
    key: "alt+left",
    description: "向后移动一帧",
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: "前进一帧",
    key: "alt+right",
    description: "向前移动一帧",
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: "上一关键帧",
    key: "ctrl+alt+left",
    description: "跳转到上一个关键帧",
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: "下一关键帧",
    key: "ctrl+alt+right",
    description: "跳转到下一个关键帧",
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: "向后跳转",
    key: "alt+left",
    description: "视频向后跳转",
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: "首帧",
    key: "shift+ctrl+alt+left",
    description: "跳转到视频首帧",
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: "向前跳转",
    key: "shift+alt+right",
    description: "视频向前跳转",
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: "尾帧",
    key: "shift+ctrl+alt+right",
    description: "跳转到视频尾帧",
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: "快速后退",
    key: "shift+alt+left",
    description: "快速向后跳转",
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: "快速前进",
    key: "shift+alt+right",
    description: "快速向前跳转",
    active: true,
  },

  // 编辑器 - 时间序列控制
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: "向左扩展",
    key: "left",
    description: "将区域向左扩展",
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: "向右扩展",
    key: "right",
    description: "将区域向右扩展",
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: "从左侧收缩",
    key: "alt+left",
    description: "从左侧收缩区域",
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: "从右侧收缩",
    key: "alt+right",
    description: "从右侧收缩区域",
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: "大幅向左扩展",
    key: "shift+left",
    description: "显著向左扩展区域",
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: "大幅向右扩展",
    key: "shift+right",
    description: "显著向右扩展区域",
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: "从左侧大幅收缩",
    key: "shift+alt+left",
    description: "从左侧显著收缩区域",
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: "从右侧大幅收缩",
    key: "shift+alt+right",
    description: "从右侧显著收缩区域",
    active: true,
  },

  // 图片库控制
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: "上一张图片",
    key: "ctrl+left",
    description: "查看上一张图片",
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: "下一张图片",
    key: "ctrl+right",
    description: "查看下一张图片",
    active: true,
  },

  // 工具控制
  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: "放大",
    key: "ctrl+plus",
    description: "放大图片",
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: "平移图片",
    key: "H",
    description: "平移查看图片",
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: "缩放以适应",
    key: "shift+1",
    description: "缩放以完整显示图片",
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: "缩放至100%",
    key: "shift+2",
    description: "缩放至图片实际大小（100%）",
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: "缩小",
    key: "ctrl+minus",
    description: "缩小图片",
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: "移动工具",
    key: "V",
    description: "选择移动工具以重新定位标注",
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: "画笔工具",
    key: "B",
    description: "选择画笔工具",
    active: true,
  },
  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: "椭圆工具",
    key: "O",
    description: "选择椭圆工具",
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: "橡皮工具",
    key: "E",
    description: "选择橡皮工具",
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: "自动检测",
    key: "M",
    description: "使用自动检测工具智能推荐区域",
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: "关键点工具",
    key: "K",
    description: "选择关键点标注工具",
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: "魔棒工具",
    key: "W",
    description: "选择魔棒工具进行智能区域选择",
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: "多边形工具",
    key: "P",
    description: "选择多边形标注工具",
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: "矩形工具",
    key: "R",
    description: "选择矩形标注工具",
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: "三点矩形",
    key: "shift+R",
    description: "使用三点定位绘制旋转矩形",
    active: true,
  },
  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: "向左旋转",
    key: "alt+left",
    description: "将图片向左旋转90°",
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: "向右旋转",
    key: "alt+right",
    description: "将图片向右旋转90°",
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: "减小工具尺寸",
    key: "[",
    description: "减小工具尺寸",
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: "增大工具尺寸",
    key: "]",
    description: "增大工具尺寸",
    active: true,
  },

  // 段落导航
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: "下一短语",
    key: "ctrl+down",
    description: "在段落视图中导航到下一个短语",
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: "上一短语",
    key: "ctrl+up",
    description: "在段落视图中导航到上一个短语",
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: "全选并标注",
    key: "ctrl+shift+a",
    description: "全选当前短语文本并创建标注",
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: "短语内下一区域",
    key: "ctrl+right",
    description: "导航到当前短语内的下一个区域",
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: "短语内上一区域",
    key: "ctrl+left",
    description: "导航到当前短语内的上一个区域",
    active: true,
  },
];

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: "标注操作",
    description: "提交、跳过、撤销和重做等常用标注任务的快捷键",
  },
  {
    id: "data_manager",
    title: "数据管理器",
    description: "在项目数据管理器中导航和管理任务的快捷键",
  },
  {
    id: "regions",
    title: "区域管理",
    description: "创建、选择和操作标注区域的快捷键",
  },
  {
    id: "tools",
    title: "工具控制",
    description: "标注图片时控制工具面板的快捷键",
  },
  {
    id: "audio",
    title: "音频控制",
    description: "控制音频播放和导航的快捷键",
  },
  {
    id: "video",
    title: "视频控制",
    description: "控制视频播放和导航的快捷键",
  },
  {
    id: "timeseries",
    title: "时间序列控制",
    description: "操作时间序列数据区域的快捷键",
  },
  {
    id: "image_gallery",
    title: "图片库导航",
    description: "在多图片任务中切换图片的快捷键",
  },
  {
    id: "paragraphs",
    title: "段落导航",
    description: "在段落/对话视图中导航短语和区域的快捷键",
  },
];


/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
